[package]
name = "grammar"
version = "0.1.0"
authors = ["IATOW <584130248@qq.com>"]
edition = "2018"

[dependencies]
prettytable-rs = "0.8.0"
clap = "2.33.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
rand = "0.7.3"

[profile.release]
opt-level = 3